ethstats:
  fullnameOverride: ethstats

  image:
    repository: skylenet/ethstats-server
    tag: poa-no-geoip

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: ethstats.testing-devnet.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  secretEnv:
    #WS_SECRET: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.testing-devnets.ethstats_secret}>"
    WS_SECRET: "testingdevnetSuperSecret" # it's in clear text on purpose
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
